# Generated by Django 5.0 on 2024-02-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('amount', models.TextField()),
                ('purpose', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
            ],
        ),
    ]
